api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/ApiResource']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header